spring.application.name=hr-os-lite

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/hr_os_lite
spring.datasource.username=root
spring.datasource.password=root@111

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# SERVER
server.port=8080